//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.15 at 11:44:13 PM MSK 
//


package ru.demo.esf.soap.bindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for errorCodesResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="errorCodesResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="errorDescriptions"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="errorDescription" type="{esf}errorDescription" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "errorCodesResponse", namespace = "esf", propOrder = {
    "errorDescriptions"
})
public class ErrorCodesResponse {

    @XmlElement(required = true)
    protected ErrorCodesResponse.ErrorDescriptions errorDescriptions;

    /**
     * Gets the value of the errorDescriptions property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorCodesResponse.ErrorDescriptions }
     *     
     */
    public ErrorCodesResponse.ErrorDescriptions getErrorDescriptions() {
        return errorDescriptions;
    }

    /**
     * Sets the value of the errorDescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorCodesResponse.ErrorDescriptions }
     *     
     */
    public void setErrorDescriptions(ErrorCodesResponse.ErrorDescriptions value) {
        this.errorDescriptions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="errorDescription" type="{esf}errorDescription" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "errorDescription"
    })
    public static class ErrorDescriptions {

        protected List<ErrorDescription> errorDescription;

        /**
         * Gets the value of the errorDescription property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the errorDescription property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getErrorDescription().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ErrorDescription }
         * 
         * 
         */
        public List<ErrorDescription> getErrorDescription() {
            if (errorDescription == null) {
                errorDescription = new ArrayList<ErrorDescription>();
            }
            return this.errorDescription;
        }

    }

}
